import Head from 'next/head'
import Sidebar from '../components/Sidebar'
import MiddleBar from '../components/MiddleBar'
import ChatScreen from '../components/ChatScreen'

export default function Home() {
    return (
        <div>
            <Head>
                <title>Discord</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <div className="flex">
                <Sidebar />
                <MiddleBar />
                <ChatScreen />
            </div>
        </div>
    )
}
